import type { Client, Settings } from '../types';
import { uid } from './utils';

const daysAgo = (days: number, hourOffset = 0): number => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(10 + hourOffset, 24, 0, 0);
  return d.getTime();
};

const futureDate = (days: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
};

export function buildSampleClients(): Client[] {
  const base: Omit<Client, 'id'>[] = [
    {
      name: 'Aarav Mehta',
      company: 'ABC Furniture',
      email: 'aarav@abcfurniture.in',
      phone: '+91 98200 11223',
      whatsapp: '+91 98200 11223',
      country: 'India',
      city: 'Mumbai',
      address: '14, Andheri Industrial Estate, Andheri West, Mumbai 400058',
      preferredContact: 'WhatsApp',
      clientType: 'Small Business',
      businessName: 'ABC Furniture',
      industry: 'Furniture',
      description:
        'ABC Furniture designs and handcrafts solid-wood furniture — living room sets, dining tables, wardrobes and modular kitchens — for homes and offices across Mumbai. They sell both retail and through interior designer partners, and want to grow their direct online enquiries.',
      yearsInBusiness: '12',
      existingWebsite: 'https://abcfurniture.in',
      instagram: 'https://instagram.com/abc.furniture',
      facebook: 'https://facebook.com/abcfurniture',
      linkedin: '',
      otherSocial: '',
      projectType: 'E-commerce',
      projectGoal:
        'Showcase the furniture catalogue with high-quality photography and convert homeowners and interior designers into quote requests and showroom visits.',
      targetAudience:
        'Homeowners and interior designers in Mumbai looking for handcrafted, custom-made wooden furniture.',
      deadline: futureDate(21),
      budget: '₹50,000 – ₹1,00,000',
      pages: ['Home', 'Shop', 'Products', 'About', 'Contact', 'FAQ'],
      customPages: ['Custom Furniture'],
      features: ['WhatsApp Integration', 'Contact Form', 'Search', 'Shopping Cart', 'Payment Gateway'],
      customFeatures: ['Quote Request Form'],
      contentProvider: 'Client',
      notes:
        'Client will provide product photography from their studio. Wants a WhatsApp button on every product card and a quick quote form on each product. Favours warm, natural wood tones in the design.',
      theme: 'modern-minimal',
      status: 'Requirement Collected',
      createdAt: daysAgo(21, 2),
      updatedAt: daysAgo(1, 4),
      dynamicAnswers: {
        'ecom-categories': true,
        'ecom-product-count': '80–120',
        'ecom-variants': true,
        'ecom-cart': true,
        'ecom-wishlist': false,
        'ecom-accounts': false,
        'ecom-guest-checkout': true,
        'ecom-payment': true,
        'ecom-shipping': true,
        'ecom-order-tracking': false,
        'ecom-coupons': true,
        'ecom-inventory': false,
        'ecom-reviews': true,
        'ecom-payment-providers': ['Razorpay', 'Cash on Delivery'],
        'ecom-shipping-providers': ['Delhivery'],
      },
    },
    {
      name: 'Meera Krishnan',
      company: 'Urban Brew',
      email: 'meera@urbanbrew.in',
      phone: '+91 99870 44556',
      whatsapp: '+91 99870 44556',
      country: 'India',
      city: 'Bengaluru',
      address: '22, Church Street, Bengaluru 560001',
      preferredContact: 'Email',
      clientType: 'Individual',
      businessName: 'Urban Brew',
      industry: 'Restaurant',
      description:
        'Urban Brew is a craft brewery and kitchen in the heart of Bengaluru — house-brewed beers, wood-fired pizzas and weekend live music in a relaxed industrial space. They host private events and want a site that captures the lively, premium experience and drives table reservations.',
      yearsInBusiness: '6',
      existingWebsite: '',
      instagram: 'https://instagram.com/urbanbrewblr',
      facebook: 'https://facebook.com/urbanbrewblr',
      linkedin: '',
      otherSocial: '',
      projectType: 'Restaurant',
      projectGoal:
        'Showcase the beer and food menus and the ambience, and drive direct table reservations and event enquiries through the website.',
      targetAudience:
        'Craft-beer lovers, foodies and corporate clients in Bengaluru looking for a premium brewpub experience and private events.',
      deadline: futureDate(14),
      budget: '₹1,00,000 – ₹2,00,000',
      pages: ['Home', 'About', 'Menu', 'Private Events', 'Gallery', 'Contact'],
      customPages: ['Reservations'],
      features: ['Booking System', 'Google Maps', 'Gallery', 'WhatsApp Integration', 'SEO'],
      customFeatures: ['Online Table Reservation'],
      contentProvider: 'Agency',
      notes:
        'Food and beer photography shoot is scheduled with our team. Reservation widget must integrate with their existing booking partner. Warm, moody, editorial feel preferred.',
      theme: 'editorial',
      status: 'In Progress',
      createdAt: daysAgo(45, 1),
      updatedAt: daysAgo(6, 3),
      dynamicAnswers: {
        'rest-menu': true,
        'rest-online-ordering': false,
        'rest-table-reservation': true,
        'rest-reservation-system': true,
        'rest-map': true,
        'rest-hours': true,
        'rest-gallery': true,
        'rest-whatsapp': true,
        'rest-delivery': false,
        'rest-pickup': true,
        'rest-branches': false,
      },
    },
    {
      name: 'Rohan Kapoor',
      company: 'Nova Properties',
      email: 'rohan@novaproperties.in',
      phone: '+91 98100 77889',
      whatsapp: '+91 98100 77889',
      country: 'India',
      city: 'Gurugram',
      address: 'Tower B, Cyber City, DLF Phase 2, Gurugram 122002',
      preferredContact: 'Phone',
      clientType: 'Agency',
      businessName: 'Nova Properties',
      industry: 'Real Estate',
      description:
        'Nova Properties is a full-service real estate agency handling residential and commercial properties across Gurugram and NCR. They represent premium builders and also resell luxury apartments. They need a modern portal to list properties and capture serious buyer enquiries.',
      yearsInBusiness: '15',
      existingWebsite: 'https://novaproperties.in',
      instagram: 'https://instagram.com/novaproperties',
      facebook: 'https://facebook.com/novaproperties',
      linkedin: 'https://linkedin.com/company/novaproperties',
      otherSocial: '',
      projectType: 'Real Estate',
      projectGoal:
        'Build a premium property listing portal where buyers can browse projects, shortlist properties and book site visits.',
      targetAudience:
        'High-net-worth individuals and corporate clients looking to buy or rent premium residential and commercial property in NCR.',
      deadline: futureDate(30),
      budget: '₹2,00,000+',
      pages: ['Home', 'Properties', 'Projects', 'Agents', 'About', 'Blog', 'Contact'],
      customPages: ['Site Visit Booking'],
      features: ['Search', 'Contact Form', 'WhatsApp Integration', 'Google Maps', 'Analytics', 'SEO'],
      customFeatures: ['Property Shortlist', 'EMI Calculator'],
      contentProvider: 'Not Decided',
      notes:
        'Property data will come from their existing CRM via CSV exports. Needs an EMI calculator widget on every property page. Thumbnails must be optimised for fast mobile loading.',
      theme: 'dark-premium',
      status: 'Review',
      createdAt: daysAgo(12, 2),
      updatedAt: daysAgo(0, 2),
      dynamicAnswers: {
        're-listings': true,
        're-search': true,
        're-filters': true,
        're-detail-pages': true,
        're-buy-rent': ['Buy', 'Rent'],
        're-agents': true,
        're-map': true,
        're-inquiry': true,
        're-submission': true,
        're-featured': true,
      },
    },
    {
      name: 'Ananya Iyer',
      company: 'FlowAI',
      email: 'ananya@flowai.tech',
      phone: '+91 99000 33445',
      whatsapp: '',
      country: 'India',
      city: 'Pune',
      address: 'WeWork Pavilion, Baner Road, Pune 411045',
      preferredContact: 'Email',
      clientType: 'Startup',
      businessName: 'FlowAI',
      industry: 'Technology',
      description:
        'FlowAI builds an AI workflow automation platform for freelancers and small agencies — automating invoicing, follow-ups and project admin in one dashboard. Backed by a pre-seed round, they are launching publicly in two months and need a marketing site that converts trial sign-ups.',
      yearsInBusiness: '2',
      existingWebsite: '',
      instagram: '',
      facebook: '',
      linkedin: 'https://linkedin.com/company/flowai',
      otherSocial: 'https://twitter.com/flowai_tech',
      projectType: 'SaaS',
      projectGoal:
        'Launch a product marketing website with a clear value proposition, feature tour and frictionless free-trial sign-up.',
      targetAudience:
        'Freelancers, designers and small agencies in India struggling with manual admin and late payments.',
      deadline: futureDate(28),
      budget: '₹1,00,000 – ₹2,00,000',
      pages: ['Home', 'Features', 'Pricing', 'Blog', 'Contact'],
      customPages: ['Security'],
      features: ['User Login', 'User Registration', 'Newsletter', 'Blog/CMS', 'Analytics', 'SEO'],
      customFeatures: ['Free Trial Signup', 'Product Changelog'],
      contentProvider: 'AI Generated',
      notes:
        'Brand kit is ready (logo, fonts, colours). Need a privacy page and cookie banner. Copy will be drafted by our team using their feature docs.',
      theme: 'bento-saas',
      status: 'Requirement Collected',
      createdAt: daysAgo(5, 3),
      updatedAt: daysAgo(0, 1),
      dynamicAnswers: {
        'saas-auth': true,
        'saas-registration': true,
        'saas-login': true,
        'saas-dashboard': true,
        'saas-plans': true,
        'saas-trial': true,
        'saas-billing': true,
        'saas-profile': true,
        'saas-admin': false,
        'saas-usage': true,
      },
    },
    {
      name: 'Neha Gupta',
      company: 'Studio Forma',
      email: 'neha@studioforma.in',
      phone: '+91 97690 22110',
      whatsapp: '+91 97690 22110',
      country: 'India',
      city: 'Jaipur',
      address: 'Shop 4, Civil Lines Market, Jaipur 302006',
      preferredContact: 'Instagram',
      clientType: 'Small Business',
      businessName: 'Studio Forma',
      industry: 'Interior Design',
      description:
        'Studio Forma is a Jaipur-based interior design studio specialising in residential and commercial interiors — space planning, materials and styling with a contemporary Indian sensibility. They win work through their portfolio and word of mouth, and want a site that presents their projects beautifully.',
      yearsInBusiness: '4',
      existingWebsite: '',
      instagram: 'https://instagram.com/studioforma.design',
      facebook: 'https://facebook.com/studioforma',
      linkedin: '',
      otherSocial: '',
      projectType: 'Portfolio',
      projectGoal:
        'Present completed projects as a visual portfolio and convert visitors into design consultations.',
      targetAudience:
        'Homeowners and boutique commercial clients in Jaipur looking for thoughtful, contemporary interior design.',
      deadline: futureDate(35),
      budget: '₹50,000 – ₹1,00,000',
      pages: ['Home', 'About', 'Projects', 'Services', 'Testimonials', 'Contact'],
      customPages: ['Our Process'],
      features: ['Contact Form', 'Gallery', 'WhatsApp Integration', 'Social Media Integration', 'SEO'],
      customFeatures: ['Consultation Booking'],
      contentProvider: 'Client',
      notes:
        'Client will supply high-resolution project photography. Wants project categories (residential, commercial, retail). No prices shown — consultations via form or WhatsApp.',
      theme: 'aurora-glass',
      status: 'Draft',
      createdAt: daysAgo(2, 1),
      updatedAt: daysAgo(2, 1),
      dynamicAnswers: {
        'port-projects': true,
        'port-gallery': true,
        'port-testimonials': true,
        'port-services': true,
        'port-resume': false,
      },
    },
  ];

  return base.map((c) => ({ ...c, id: uid() }));
}

export const DEFAULT_SETTINGS: Settings = {
  agencyName: 'Your Agency',
  logo: '',
  email: 'hello@youragency.com',
  phone: '+91 90000 00000',
  defaultCurrency: '₹ (INR)',
  pdfFooter: 'Prepared with care by Your Agency',
  defaultTheme: 'modern-minimal',
  aiProvider: 'local',
  aiEndpoint: '',
  aiApiKey: '',
  aiModel: 'gpt-4o-mini',
};